export default {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  LOGOUT: 'LOGOUT',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  GET_LAZY_LOADER_DATA: 'GET_LAZY_LOADER_DATA',
  LOAD_SETTING: 'LOAD_SETTING'
};
